// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjJXVgHaR009xDXAOhKTzeI2YBD6FioY',
    appId: '1:794254645766:web:186d8e4d8d89495af40187',
    messagingSenderId: '794254645766',
    projectId: 'poker-f74e3',
    authDomain: 'poker-f74e3.firebaseapp.com',
    storageBucket: 'poker-f74e3.firebasestorage.app',
    measurementId: 'G-RWHQ0XWY88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5gELz3A1HPhx1UDAmUj--_Hk-w-89BxI',
    appId: '1:794254645766:android:8176a30d0f973252f40187',
    messagingSenderId: '794254645766',
    projectId: 'poker-f74e3',
    storageBucket: 'poker-f74e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHh3exdU2xSCef7ffFSrGBzoK0vCwk3Zo',
    appId: '1:794254645766:ios:80b4b50ec832e832f40187',
    messagingSenderId: '794254645766',
    projectId: 'poker-f74e3',
    storageBucket: 'poker-f74e3.firebasestorage.app',
    iosBundleId: 'com.example.poker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHh3exdU2xSCef7ffFSrGBzoK0vCwk3Zo',
    appId: '1:794254645766:ios:80b4b50ec832e832f40187',
    messagingSenderId: '794254645766',
    projectId: 'poker-f74e3',
    storageBucket: 'poker-f74e3.firebasestorage.app',
    iosBundleId: 'com.example.poker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjJXVgHaR009xDXAOhKTzeI2YBD6FioY',
    appId: '1:794254645766:web:526d2e7cba4e30b3f40187',
    messagingSenderId: '794254645766',
    projectId: 'poker-f74e3',
    authDomain: 'poker-f74e3.firebaseapp.com',
    storageBucket: 'poker-f74e3.firebasestorage.app',
    measurementId: 'G-BHW4SWSN17',
  );
}
